import { Demand } from "@/types/demand";

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const INITIAL_MOCK_DEMANDS: Demand[] = [
  {
    id: "f84b64a2-1e94-4d80-87a4-e9f029141001",
    title: "Butuh Supplier Biji Kopi Robusta & Arabica 500kg/bulan",
    raw_content: "Halo rekan-rekan, ada yang punya link supplier biji kopi Robusta Temanggung & Arabica Gayo untuk roastery baru di Jaksel? Butuh supply rutin minimal 500kg/bulan dengan grade fine commercial/specialty. DM atau kontak WA 081234567890. Terima kasih.",
    summary: "Mencari supplier biji kopi Robusta & Arabica rutin 500kg/bulan untuk kebutuhan roastery di Jakarta Selatan.",
    item_or_service: "Biji Kopi Robusta & Arabica",
    category: "supplier",
    source_platform: "twitter",
    source_url: "https://twitter.com/kopijakarta/status/178901234567890001",
    location_name: "Jakarta Selatan, DKI Jakarta",
    latitude: -6.2615,
    longitude: 106.8106,
    is_solved: false,
    confidence_score: 0.98,
    contact_target: "WA: 081234567890 / @kopijakarta",
    posted_at: hoursAgo(2),
    created_at: hoursAgo(2),
  },
  {
    id: "f84b64a2-1e94-4d80-87a4-e9f029141002",
    title: "Dicari Jasa Import Borongan Door-to-Door dari Yiwu ke Surabaya",
    raw_content: "URGENT! Butuh jasa forwarder impor borongan resmi/door to door dari Yiwu China ke Pergudangan Margomulyo Surabaya. Barang aksesoris HP sekitar 3 CBM. Ada rekomendasi freight forwarder terpercaya yang amanah? PM rate per CBM ya.",
    summary: "Kebutuhan jasa forwarder impor door-to-door China-Surabaya 3 CBM aksesoris HP.",
    item_or_service: "Jasa Import Borongan Forwarder China-Surabaya",
    category: "impor",
    source_platform: "telegram",
    source_url: "https://t.me/impor_indonesia_group/89412",
    location_name: "Surabaya, Jawa Timur",
    latitude: -7.2575,
    longitude: 112.7521,
    is_solved: false,
    confidence_score: 0.96,
    contact_target: "Telegram: @import_buyer_sub",
    posted_at: hoursAgo(4),
    created_at: hoursAgo(4),
  },
  {
    id: "f84b64a2-1e94-4d80-87a4-e9f029141003",
    title: "WTB 20 Unit Monitor 24 Inch IPS 75Hz untuk Kantor Baru",
    raw_content: "WTB / Cari 20 unit monitor kantor ukuran 24 inch panel IPS (merk LG/Samsung/AOC). Diutamakan toko/distributor area Bandung biar bisa COD atau kirim sameday. Budget 1.2jt - 1.5jt per unit. Faktur pajak diutamakan.",
    summary: "Membeli 20 unit monitor 24 inch IPS untuk pengadaan kantor di Bandung.",
    item_or_service: "Monitor 24 Inch IPS 20 Unit",
    category: "barang",
    source_platform: "forum",
    source_url: "https://kaskus.co.id/thread/6620f91823901/wtb-20-unit-monitor-kantor-bandung",
    location_name: "Bandung, Jawa Barat",
    latitude: -6.9175,
    longitude: 107.6191,
    is_solved: false,
    confidence_score: 0.94,
    contact_target: "Email: procurement@techstartup.id",
    posted_at: hoursAgo(6),
    created_at: hoursAgo(6),
  },
  {
    id: "f84b64a2-1e94-4d80-87a4-e9f029141004",
    title: "Cari Vendor Konveksi Kaos Polo Bordir Komunitas 300 Pcs",
    raw_content: "Dicari vendor konveksi untuk pengerjaan 300 pcs kaos polo bordir bahan lacoste pique. Deadline 2 minggu pengerjaan. Lokasi workshop Tangerang/Jakarta Barat lebih disukai agar bisa cek sample kain langsung. Portofolio kirim ke DM.",
    summary: "Mencari vendor konveksi kaos polo bordir 300 pcs deadline 2 minggu.",
    item_or_service: "Jasa Konveksi Kaos Polo Bordir 300 Pcs",
    category: "jasa",
    source_platform: "twitter",
    source_url: "https://twitter.com/event_id/status/178904561234567890",
    location_name: "Tangerang, Banten",
    latitude: -6.1783,
    longitude: 106.6319,
    is_solved: false,
    confidence_score: 0.95,
    contact_target: "Twitter DM @event_id",
    posted_at: hoursAgo(8),
    created_at: hoursAgo(8),
  },
  {
    id: "f84b64a2-1e94-4d80-87a4-e9f029141005",
    title: "WTB Kardus Box Corrugated Die Cut Custom 2000 Pcs",
    raw_content: "Sudah dapet ya vendornya dari Mas Budi CV Karton Abadi Semarang. CLOSED! Terima kasih teman-teman grup yang sudah bantu rekomen.",
    summary: "Pengadaan kardus box die-cut custom 2000 pcs (sudah terpenuhi / closed).",
    item_or_service: "Kardus Box Corrugated Die Cut",
    category: "barang",
    source_platform: "facebook",
    source_url: "https://facebook.com/groups/umkm.packaging/permalink/992817263541/",
    location_name: "Semarang, Jawa Tengah",
    latitude: -6.9667,
    longitude: 110.4167,
    is_solved: true,
    confidence_score: 0.99,
    contact_target: "FB: Andi Packaging",
    posted_at: daysAgo(1),
    created_at: daysAgo(1),
  },
  {
    id: "f84b64a2-1e94-4d80-87a4-e9f029141006",
    title: "Looking for Indonesian Furniture Manufacturer (Teak & Rattan Export)",
    raw_content: "We are a boutique hospitality interior studio based in Melbourne, Australia. We are actively sourcing reliable verified manufacturers in Jepara for custom teak dining chairs and synthetic rattan lounge sets (1x 40ft HQ Container). Inspection report required.",
    summary: "Australian buyer seeking verified Indonesian teak & rattan furniture manufacturers for export container.",
    item_or_service: "Teak & Rattan Furniture Export Manufacturer",
    category: "impor",
    source_platform: "reddit",
    source_url: "https://reddit.com/r/indonesia/comments/1cxyza/looking_for_teak_furniture_supplier_export/",
    location_name: "Jepara, Jawa Tengah",
    latitude: -6.5888,
    longitude: 110.6684,
    is_solved: false,
    confidence_score: 0.97,
    contact_target: "Reddit: u/AussieDesignStudio",
    posted_at: daysAgo(1),
    created_at: daysAgo(1),
  },
  {
    id: "f84b64a2-1e94-4d80-87a4-e9f029141007",
    title: "Butuh Jasa Ekspedisi Pendingin (Reefer Truck) Jakarta-Bali",
    raw_content: "Butuh vendor truk reefer pendingin kapasitas 5 ton rute Jakarta - Denpasar untuk angkut frozen seafood. Jadwal rutin tiap pekan hari Selasa. Ada rekomendasi ekspedisi yang suhunya stabil minus 18 derajat?",
    summary: "Mencari penyedia jasa truk pendingin / reefer rutin Jakarta ke Denpasar Bali.",
    item_or_service: "Jasa Truk Pendingin (Reefer Truck)",
    category: "jasa",
    source_platform: "telegram",
    source_url: "https://t.me/logistik_nusantara/5129",
    location_name: "Denpasar, Bali",
    latitude: -8.6705,
    longitude: 115.2126,
    is_solved: false,
    confidence_score: 0.92,
    contact_target: "WA: 087812984711",
    posted_at: daysAgo(1),
    created_at: daysAgo(1),
  },
  {
    id: "f84b64a2-1e94-4d80-87a4-e9f029141008",
    title: "Supplier Bahan Baku Tepung Tapioka Kasar 10 Ton",
    raw_content: "Dicari pabrik/supplier tangan pertama tepung tapioka kasar kualitas industri pakan & kerupuk. Kebutuhan 10 ton per pengiriman ke gudang Medan Deli. Tolong sertakan spesifikasi kadar air dan harga loco gudang.",
    summary: "Kebutuhan tepung tapioka kasar skala industri 10 ton pengiriman ke Medan Deli.",
    item_or_service: "Tepung Tapioka Kasar 10 Ton",
    category: "supplier",
    source_platform: "forum",
    source_url: "https://agrobisnis.id/threads/butuh-tapioka-medan-10-ton.4421/",
    location_name: "Medan, Sumatera Utara",
    latitude: 3.5952,
    longitude: 98.6722,
    is_solved: false,
    confidence_score: 0.93,
    contact_target: "Telp: 085270112233 (Pak Hendra)",
    posted_at: daysAgo(2),
    created_at: daysAgo(2),
  }
];
